#pragma once

/// \file position.hpp
/// A single instrument position with weighted-average-cost accounting.
///
/// ADR: weighted average cost, not FIFO lots (Phase 1 review, P-1). Simpler to
/// get right, and the lot methodology sits behind this type so FIFO can replace
/// it without touching the portfolio.
///
/// The case that breaks naive implementations is a REVERSAL: a long position
/// sold through zero into a short. The realised P&L must be computed on the
/// closing portion only, and the cost basis must RESET at zero -- carrying the
/// old average across would leave the short marked against a long's entry
/// price, and every subsequent unrealised number would be wrong.

#include <cmath>

#include "ptl/core/types.hpp"
#include "ptl/oms/fill.hpp"

namespace ptl::portfolio {

class Position {
public:
    explicit Position(InstrumentId instrument = kInvalidInstrument) noexcept
        : instrument_(instrument) {}

    /// \returns realised P&L generated by this fill (zero when only opening).
    Notional apply(const oms::Fill& fill);

    /// Adjust for a split. `ratio` is new shares per old share.
    void apply_split(double ratio) noexcept;

    /// Cash dividend on the held quantity. A short position PAYS it.
    [[nodiscard]] Notional dividend_cash(Notional per_share) const noexcept;

    [[nodiscard]] InstrumentId instrument() const noexcept { return instrument_; }
    [[nodiscard]] Qty quantity() const noexcept { return quantity_; }
    [[nodiscard]] Price average_cost() const noexcept { return average_cost_; }
    [[nodiscard]] Notional realized_pnl() const noexcept { return realized_; }
    [[nodiscard]] Notional total_commission() const noexcept { return commission_; }
    [[nodiscard]] Qty total_bought() const noexcept { return bought_; }
    [[nodiscard]] Qty total_sold() const noexcept { return sold_; }

    [[nodiscard]] bool is_flat() const noexcept { return quantity_.get() == 0.0; }
    [[nodiscard]] bool is_long() const noexcept { return quantity_.get() > 0.0; }
    [[nodiscard]] bool is_short() const noexcept { return quantity_.get() < 0.0; }

    /// Signed market value at `mark`.
    [[nodiscard]] Notional market_value(Price mark) const noexcept {
        return Notional{quantity_.get() * mark.get()};
    }
    [[nodiscard]] Notional unrealized_pnl(Price mark) const noexcept {
        if (is_flat()) return Notional{0.0};
        return Notional{(mark.get() - average_cost_.get()) * quantity_.get()};
    }
    [[nodiscard]] Notional gross_exposure(Price mark) const noexcept {
        return Notional{std::abs(quantity_.get()) * mark.get()};
    }

private:
    InstrumentId instrument_{kInvalidInstrument};
    Qty quantity_{};
    Price average_cost_{};
    Notional realized_{};
    Notional commission_{};
    Qty bought_{};
    Qty sold_{};
};

}  // namespace ptl::portfolio
