#pragma once

/// \file broker.hpp
/// The simulated venue: the ONLY component in the system that can create a Fill.
///
/// Fill's constructor is private and BrokerSimulator is its sole friend. No
/// strategy, no test helper, no analytics pass can fabricate an execution. That
/// single restriction is what makes the equity curve trustworthy -- every
/// dollar traces to one place, and reviewing execution correctness means
/// reviewing one file.
///
/// Assumptions, all configurable and all documented in
/// docs/03-execution-assumptions.md:
///   - orders arrive after a modelled latency, never at their decision instant;
///   - marketable orders cross the spread and pay impact;
///   - fills are capped by displayed size and participation rate;
///   - a resting limit does not fill on a touch alone.

#include <memory>
#include <vector>

#include "ptl/core/clock.hpp"
#include "ptl/core/result.hpp"
#include "ptl/core/rng.hpp"
#include "ptl/execution/models.hpp"
#include "ptl/oms/fill.hpp"
#include "ptl/oms/order.hpp"

namespace ptl::execution {

/// One pending order inside the venue, with the instant it becomes live.
struct PendingOrder {
    oms::Order order;
    Timestamp arrival_time{kNoTimestamp};
    Qty filled{};
};

struct ExecutionStats {
    std::size_t orders_accepted = 0;
    std::size_t orders_rejected = 0;
    std::size_t fills = 0;
    std::size_t partial_fills = 0;
    std::size_t participation_capped = 0;
    std::size_t displayed_size_capped = 0;
    std::size_t passive_no_fill = 0;
    Notional total_commission{};
    Notional total_impact_cost{};
};

class BrokerSimulator {
public:
    /// \param clock borrowed; the venue reads simulated time from it.
    /// \param rng   forked per-stream so adding a consumer cannot perturb fills.
    BrokerSimulator(const IClock& clock, const ICostModel& costs, const ILatencyModel& latency,
                    DeterministicRng rng, FillConfig fill_cfg = {});

    /// Accept an order. Its arrival time is stamped here, strictly after its
    /// decision time, so same-bar execution is impossible by construction.
    [[nodiscard]] Result<Timestamp> submit(const oms::Order& order);

    [[nodiscard]] Result<bool> cancel(oms::OrderId id);

    /// Advance the venue to `state` at `now`, producing any fills that result.
    /// Returns the fills generated by THIS call.
    [[nodiscard]] Result<std::vector<oms::Fill>> on_market(InstrumentId instrument,
                                                           const MarketState& state, Timestamp now);

    [[nodiscard]] const ExecutionStats& stats() const noexcept { return stats_; }
    [[nodiscard]] std::size_t pending_count() const noexcept { return pending_.size(); }
    void reset() noexcept;

private:
    [[nodiscard]] Result<oms::Fill> make_fill(const oms::Order& order, Price price, Qty qty,
                                              Timestamp now, oms::Liquidity liquidity);

    const IClock* clock_;
    const ICostModel* costs_;
    const ILatencyModel* latency_;
    DeterministicRng latency_rng_;
    DeterministicRng slippage_rng_;
    FillConfig fill_cfg_;
    std::vector<PendingOrder> pending_;
    ExecutionStats stats_;
};

}  // namespace ptl::execution
