#pragma once

/// \file broker.hpp
/// The simulated venue: the ONLY component in the system that can create a Fill.
///
/// Fill's constructor is private and BrokerSimulator is its sole friend. No
/// strategy, no test helper, no analytics pass can fabricate an execution. That
/// single restriction is what makes the equity curve trustworthy -- every
/// dollar traces to one place, and reviewing execution correctness means
/// reviewing one file.
///
/// Assumptions, all configurable and all documented in
/// docs/03-execution-assumptions.md:
///   - orders arrive after a modelled latency, never at their decision instant;
///   - marketable orders cross the spread and pay impact;
///   - fills are capped by displayed size and participation rate;
///   - a resting limit does not fill on a touch alone.

#include <memory>
#include <vector>

#include "ptl/core/clock.hpp"
#include "ptl/core/result.hpp"
#include "ptl/core/rng.hpp"
#include "ptl/execution/models.hpp"
#include "ptl/execution/quote_router.hpp"
#include "ptl/oms/fill.hpp"
#include "ptl/oms/order.hpp"

namespace ptl::execution {

/// One pending order inside the venue, with the instant it becomes live.
struct PendingOrder {
    oms::Order order;
    Timestamp arrival_time{kNoTimestamp};
    Qty filled{};
    /// Stop and stop-limit orders are DORMANT until their stop price trades
    /// through. is_marketable_against() reports true for a stop unconditionally
    /// -- correct once triggered -- so this flag is what keeps a protective
    /// stop from filling the instant it arrives.
    bool stop_triggered = false;
};

struct ExecutionStats {
    std::size_t orders_accepted = 0;
    std::size_t orders_rejected = 0;
    std::size_t fills = 0;
    std::size_t partial_fills = 0;
    std::size_t participation_capped = 0;
    std::size_t displayed_size_capped = 0;
    std::size_t passive_no_fill = 0;
    std::size_t stops_triggered = 0;
    std::size_t fok_killed = 0;
    std::size_t rejected_stale_quote = 0;
    std::size_t rejected_halted = 0;
    std::size_t rejected_crossed = 0;
    std::size_t filled_from_quote = 0;
    std::size_t filled_from_bar = 0;
    Notional total_commission{};
    Notional total_impact_cost{};
};

/// A fill as reported by an external venue.
///
/// Deliberately NOT a Fill: it is untrusted input until validated. Keeping the
/// two types distinct is what stops a broker message being mistaken for a
/// confirmed fill anywhere in the codebase.
struct ExternalFillReport {
    oms::OrderId order_id{oms::kNoOrder};
    Qty quantity{};
    Price price{};
    Timestamp fill_time{kNoTimestamp};
    Notional commission{};
    Notional exchange_fee{};
    /// Taker by default: a live fill whose liquidity flag the venue did not
    /// report is assumed to have crossed the spread, which is the conservative
    /// assumption for cost attribution.
    oms::Liquidity liquidity{oms::Liquidity::Taker};
    /// The venue's own identifier, for duplicate suppression upstream.
    std::string venue_fill_id;
};

class BrokerSimulator {
public:
    /// \param clock borrowed; the venue reads simulated time from it.
    /// \param rng   forked per-stream so adding a consumer cannot perturb fills.
    BrokerSimulator(const IClock& clock, const ICostModel& costs, const ILatencyModel& latency,
                    DeterministicRng rng, FillConfig fill_cfg = {});

    /// Accept an order. Its arrival time is stamped here, strictly after its
    /// decision time, so same-bar execution is impossible by construction.
    [[nodiscard]] Result<Timestamp> submit(const oms::Order& order);

    [[nodiscard]] Result<bool> cancel(oms::OrderId id);

    /// Advance the venue to `state` at `now`, producing any fills that result.
    /// Returns the fills generated by THIS call.
    [[nodiscard]] Result<std::vector<oms::Fill>> on_market(InstrumentId instrument,
                                                           const MarketState& state, Timestamp now);

    /// Quote-aware entry point (Phase 8).
    ///
    /// Takes a routed market rather than a bare MarketState so the venue can
    /// see WHY execution is or is not permitted -- halted, stale, crossed --
    /// and record the reason instead of silently producing no fills. "No fills"
    /// and "no fills because the instrument was halted" are different facts,
    /// and a run that cannot tell them apart cannot explain its own trade count.
    [[nodiscard]] Result<std::vector<oms::Fill>> on_quote_update(InstrumentId instrument,
                                                                 const RoutedMarket& routed,
                                                                 Timestamp now);

    /// Record a fill that happened at a REAL VENUE.
    ///
    /// WHY THIS EXISTS (Phase 15). Fill's constructor is private and this class
    /// is its sole friend, so that every dollar in the system traces to one
    /// origin. A live broker reports fills that this class did not simulate,
    /// and there are only three ways to admit them:
    ///
    ///   1. Widen Fill's friend list to the live adapter. That gives two
    ///      classes the power to mint money and the invariant is gone.
    ///   2. Synthesise a MarketState that makes the simulator produce a
    ///      matching fill. That RE-DERIVES the fill instead of recording it,
    ///      and can disagree with the quantity the venue actually reported.
    ///   3. This: a validated ingress on the one class already trusted to
    ///      construct a Fill.
    ///
    /// The invariant is preserved exactly as written -- BrokerSimulator remains
    /// the only constructor of a Fill. What is new is that it can be TOLD about
    /// a fill rather than only computing one, and the report is validated
    /// against the order it claims to fill before it is believed.
    ///
    /// \param report what the venue said happened.
    /// \returns the constructed Fill, or an error if the report is not
    ///          consistent with a known working order.
    [[nodiscard]] Result<oms::Fill> ingest_external_fill(const ExternalFillReport& report);

    [[nodiscard]] const ExecutionStats& stats() const noexcept { return stats_; }
    [[nodiscard]] std::size_t pending_count() const noexcept { return pending_.size(); }
    void reset() noexcept;

private:
    [[nodiscard]] Result<oms::Fill> make_fill(const oms::Order& order, Price price, Qty qty,
                                              Timestamp now, oms::Liquidity liquidity);

    const IClock* clock_;
    const ICostModel* costs_;
    const ILatencyModel* latency_;
    DeterministicRng latency_rng_;
    DeterministicRng slippage_rng_;
    FillConfig fill_cfg_;
    std::vector<PendingOrder> pending_;
    ExecutionStats stats_;
};

}  // namespace ptl::execution
